# Generated by Django 4.1.1 on 2022-09-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField()),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=40)),
                ('cust_email', models.CharField(max_length=50)),
                ('cust_phone', models.BigIntegerField()),
                ('cust_image', models.ImageField(upload_to='customer/')),
                ('cust_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=40)),
                ('seller_email', models.CharField(max_length=50)),
                ('seller_adds', models.CharField(default='', max_length=100)),
                ('seller_phone', models.BigIntegerField()),
                ('seller_accno', models.BigIntegerField(default=0)),
                ('seller_ifsc', models.CharField(default='', max_length=30)),
                ('seller_image', models.ImageField(upload_to='seller/')),
                ('seller_password', models.CharField(max_length=20)),
            ],
        ),
    ]
