# Generated by Django 4.1.1 on 2022-10-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
